/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SnippetsIndexImport } from './routes/snippets/index'
import { Route as SnippetsLanguageImport } from './routes/snippets/$language'

// Create Virtual Routes

const SnippetbossLazyImport = createFileRoute('/snippetboss')()
const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const SnippetbossLazyRoute = SnippetbossLazyImport.update({
  path: '/snippetboss',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/snippetboss.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SnippetsIndexRoute = SnippetsIndexImport.update({
  path: '/snippets/',
  getParentRoute: () => rootRoute,
} as any)

const SnippetsLanguageRoute = SnippetsLanguageImport.update({
  path: '/snippets/$language',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/snippetboss': {
      preLoaderRoute: typeof SnippetbossLazyImport
      parentRoute: typeof rootRoute
    }
    '/snippets/$language': {
      preLoaderRoute: typeof SnippetsLanguageImport
      parentRoute: typeof rootRoute
    }
    '/snippets/': {
      preLoaderRoute: typeof SnippetsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutLazyRoute,
  SnippetbossLazyRoute,
  SnippetsLanguageRoute,
  SnippetsIndexRoute,
])

/* prettier-ignore-end */
